version: '3.8'

services:
  n8n-mcp-server:
    build: .
    container_name: n8n-mcp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - N8N_BASE_URL=${N8N_BASE_URL:-http://n8n:5678}
      - N8N_API_KEY=${N8N_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - STREAM_HEARTBEAT_INTERVAL=${STREAM_HEARTBEAT_INTERVAL:-30000}
      - MAX_STREAM_CLIENTS=${MAX_STREAM_CLIENTS:-100}
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID:-}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET:-}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI:-}
    ports:
      - "3005:3000"
    networks:
      - traefik
      - n8n-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n-mcp.rule=Host(`n8n-mcp.${DOMAIN:-localhost}`)"
      - "traefik.http.routers.n8n-mcp.entrypoints=websecure"
      - "traefik.http.routers.n8n-mcp.tls.certresolver=letsencrypt"
      - "traefik.http.services.n8n-mcp.loadbalancer.server.port=3000"
      - "traefik.http.routers.n8n-mcp.middlewares=cors-headers"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,POST,OPTIONS,PUT,DELETE"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors-headers.headers.addvaryheader=true"
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

#  # Optional: Include N8N service for complete setup
#  n8n:
#    image: n8nio/n8n:latest
#    container_name: n8n
#    restart: unless-stopped
#    environment:
#      - N8N_BASIC_AUTH_ACTIVE=true
#      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
#      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-admin}
#      - N8N_HOST=${N8N_HOST:-n8n.localhost}
#      - N8N_PORT=5678
#      - N8N_PROTOCOL=http
#      - WEBHOOK_URL=${WEBHOOK_URL:-http://n8n.localhost/}
#      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-UTC}
#    ports:
#      - "5678:5678"
#    volumes:
#      - n8n_data:/home/node/.n8n
#    networks:
#      - traefik
#      - n8n-network
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN:-localhost}`)"
#      - "traefik.http.routers.n8n.entrypoints=websecure"
#      - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
#      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
#
#volumes:
#  n8n_data:
# 
networks:
  traefik:
    external: true
  n8n-network:
    driver: bridge
